.TH SHOPEN 1 shopen
.SH NAME
shopen \- POSIX shell implementation of xdg-open with extensions

.SH SYNOPSIS
.B shopen
{ file | url }

.SH DESCRIPTION
shopen opens a file/url in a user specified application.
shopen also implements extensions to be more suitable
as a general purpose 'plumber'. These extensions come in
the form of being able to match a file's mimetype through
regex, and matching the given input's name through regex.

.SH EXAMPLES
.SS
Opening a local file
.EX
$ shopen ~/book.pdf

.SS
Opening a URL
.EX
$ shopen https://github.com/


.SH CONFIGURATION

If using shopen just to open files, there should be no
configuration nessecary, provided you already have a
.I mimeapps.list
file in
.B $XDG_CONFIG_DIR.

If
.I mimeapps.list
doesn't exist then shopen searches through all desktop
files in the in the user's application directory followed
by the system's applicatino directory to find the proper
application to open the provided file with.

However, shopen cannot open urls without user configuration.
While this may seem like a downside, it was a deliberate design
decision, as it makes using shopen as a general purpose plumber
much easier and straightforward.

To configure the regex extensions, you need to create
.I mimerules.tsv
and
.I rerules.tsv
in
.B $XDG_CONFIG_DIR/shopen.

The way to structure these TSV files is to have the first column
contain the regex you want to match, and to have the second column
contain the command you want to run upon a successful match.
To directly use the matched string directly in your command,
you can use '%M'.


.SS Example matching any video file to be opened in mpv (mimerules.tsv)
.EX
 video/*        mpv -quiet "%M" >/dev/null

.SS Example matching YouTube watch links to be opened in mpv (rerules.tsv)
.EX
 .*(youtube.com|youtu.be)/(watch|playlist).*        mpv "%M" >/dev/null

NOTE: If you are going to copy the above lines, make sure to replace the spaces above with a tab!

.SH FILES

.IP $XDG_CONFIG_DIR/mimeapps.list
.IP $XDG_CONFIG_DIR/shopen/mimerules.tsv
.IP $XDG_CONFIG_DIR/shopen/rerules.tsv

.SH AUTHORS
Ethan Hawk

.SH COPYRIGHT
Copyright (c) 2021 \- Licensed under GPLv3+
