#!/bin/sh

SYSTEM_DESKTOP_FILES_DIR=/usr/share/applications/
USER_DESKTOP_FILES_DIR=$HOME/.local/share/applications/
MIMEAPPSLIST=${XDG_CONFIG_DIR:-$HOME/.config}/mimeapps.list
# depends: file

for f in $*
do
	DESKTOPFILE=""
	MIME_TYPE="$(file --mime-type "$f" | cut -d' ' -f2)"
	if grep -q "$MIME_TYPE" "$MIMEAPPSLIST"
	then
		WANTDESKTOPFILE=$(grep $MIME_TYPE $MIMEAPPSLIST | cut -d'=' -f2)
		echo "Want: $WANTDESKTOPFILE"
	fi
 # Look in USER_DESKTOP_FILES_DIR first

	FOUNDDESKTOP=N
	for deskf in $USER_DESKTOP_FILES_DIR*
	do
		# if we found the desktop file, save the location
		# and break the loop
		#if echo $deskf | grep -q $WANTDESKTOPFILE
		if [ "${deskf##*/}" = "$WANTDESKTOPFILE" ]
		then
			echo $deskf
			FOUNDDESKTOP=Y
			DESKTOPFILE="$(echo $deskf | grep "$WANTDESKTOPFILE")"
			break
		fi
	done

 # Now look into SYSTEM_DESKTOP_FILES_DIR

 # Only search if we didn't find it in the users desktop file
 # directory

	[ $FOUNDDESKTOP = N ] && {
		for deskf in $SYSTEM_DESKTOP_FILES_DIR*
		do
			#if echo $deskf | grep -q $WANTDESKTOPFILE
			if [ "${deskf##*/}" = "$WANTDESKTOPFILE" ]
			then
				echo $deskf
				FOUNDDESKTOP=Y
				DESKTOPFILE="$(echo $deskf | grep "$WANTDESKTOPFILE")"
				break
			fi
		done
	}

 # if we still havent found the proper desktop file, we now need to search for
 # a desktop file that can handle the proper mimetype

 # First check the user directory
	[ $FOUNDDESKTOP = N ] && {
		for deskf in $USER_DESKTOP_FILES_DIR*
		do
			if grep -q $MIME_TYPE $deskf
			then
				echo $deskf
				FOUNDDESKTOP=Y
				DESKTOPFILE=$deskf
				break
			fi
		done
	}

 # now check the system directory
	[ $FOUNDDESKTOP = N ] && {
		for deskf in $SYSTEM_DESKTOP_FILES_DIR*
		do
			if grep -q "$MIME_TYPE" $deskf
			then
				echo $deskf
				FOUNDDESKTOP=Y
				DESKTOPFILE=$deskf
				break
			fi
		done
	}

	# if DESKTOPFILE is empty, then we should exit with a 1
	# because at this point we have found no desktop file
	# to handle our mimetype
	[ "$DESKTOPFILE" = "" ] && echo "failure" && exit 1

	# Now we open up the file according to how the desktop
	# file specifies

	echo $f

	echo $DESKTOPFILE

done




